var countries = [
    ["HB3Y","Liechtenstein","LI"], 
    ["9M0","Spratly Islands","2S"],
    ["BV9","Spratly Islands","2S"],
    ["DX0","Spratly Islands","2S"],
    ["SSA","Egypt","EG"],
    ["SSB","Egypt","EG"],
    ["SSC","Egypt","EG"],
    ["SSD","Egypt","EG"],
    ["SSE","Egypt","EG"],
    ["SSF","Egypt","EG"],
    ["SSG","Egypt","EG"],
    ["SSH","Egypt","EG"],
    ["SSI","Egypt","EG"],
    ["SSJ","Egypt","EG"],
    ["SSK","Egypt","EG"],
    ["SSL","Egypt","EG"],
    ["SSM","Egypt","EG"],
    ["3DN","Fiji","FJ"],
    ["3DO","Fiji","FJ"],
    ["3DP","Fiji","FJ"],
    ["3DQ","Fiji","FJ"],
    ["3DR","Fiji","FJ"],
    ["3DS","Fiji","FJ"],
    ["3DT","Fiji","FJ"],
    ["3DU","Fiji","FJ"],
    ["3DV","Fiji","FJ"],
    ["3DW","Fiji","FJ"],
    ["3DX","Fiji","FJ"],
    ["3DY","Fiji","FJ"],
    ["3DZ","Fiji","FJ"],
    ["HB0","Liechtenstein","LI"],
    ["HBL","Liechtenstein","LI"],
    ["3DA","Swaziland","SZ"],
    ["3DB","Swaziland","SZ"],
    ["3DC","Swaziland","SZ"],
    ["3DD","Swaziland","SZ"],
    ["3DE","Swaziland","SZ"],
    ["3DF","Swaziland","SZ"],
    ["3DG","Swaziland","SZ"],
    ["3DH","Swaziland","SZ"],
    ["3DI","Swaziland","SZ"],
    ["3DJ","Swaziland","SZ"],
    ["3DK","Swaziland","SZ"],
    ["3DL","Swaziland","SZ"],
    ["3DM","Swaziland","SZ"],
    ["RA6","Chechnya",""],
    ["C3","Andorra","AD"],
    ["A6","United Arab Emirates","AE"],
    ["T6","Afghanistan","AF"],
    ["YA","Afghanistan","AF"],
    ["V2","Antigua and Barbuda","AG"],
    ["ZA","Albania","AL"],
    ["EK","Armenia","AM"],
    ["D2","Angola","AO"],
    ["D3","Angola","AO"],
    ["AY","Argentina","AR"],
    ["AZ","Argentina","AR"],
    ["L2","Argentina","AR"],
    ["L3","Argentina","AR"],
    ["L4","Argentina","AR"],
    ["L5","Argentina","AR"],
    ["L6","Argentina","AR"],
    ["L7","Argentina","AR"],
    ["L8","Argentina","AR"],
    ["L9","Argentina","AR"],
    ["LO","Argentina","AR"],
    ["LP","Argentina","AR"],
    ["LQ","Argentina","AR"],
    ["LR","Argentina","AR"],
    ["LS","Argentina","AR"],
    ["LT","Argentina","AR"],
    ["LU","Argentina","AR"],
    ["LV","Argentina","AR"],
    ["LW","Argentina","AR"],
    ["OE","Austria","AT"],
    ["AX","Australia","AU"],
    ["VH","Australia","AU"],
    ["VI","Australia","AU"],
    ["VJ","Australia","AU"],
    ["VK","Australia","AU"],
    ["VL","Australia","AU"],
    ["VM","Australia","AU"],
    ["VN","Australia","AU"],
    ["VZ","Australia","AU"],
    ["P4","Aruba","AW"],
    ["4J","Azerbaijan","AZ"],
    ["4K","Azerbaijan","AZ"],
    ["E7","Bosnia and Herzegovina","BA"],
    ["8P","Barbados","BB"],
    ["S2","Bangladesh","BD"],
    ["S3","Bangladesh","BD"],
    ["ON","Belgium","BE"],
    ["OO","Belgium","BE"],
    ["OP","Belgium","BE"],
    ["OQ","Belgium","BE"],
    ["OR","Belgium","BE"],
    ["OS","Belgium","BE"],
    ["OT","Belgium","BE"],
    ["XT","Burkina Faso","BF"],
    ["LZ","Bulgaria","BG"],
    ["A9","Bahrain","BH"],
    ["9U","Burundi","BI"],
    ["TY","Benin","BJ"],
    ["V8","Brunei","BN"],
    ["CP","Bolivia","BO"],
    ["PP","Brazil","BR"],
    ["PQ","Brazil","BR"],
    ["PR","Brazil","BR"],
    ["PS","Brazil","BR"],
    ["PT","Brazil","BR"],
    ["PU","Brazil","BR"],
    ["PV","Brazil","BR"],
    ["PW","Brazil","BR"],
    ["PX","Brazil","BR"],
    ["PY","Brazil","BR"],
    ["ZV","Brazil","BR"],
    ["ZW","Brazil","BR"],
    ["ZX","Brazil","BR"],
    ["ZY","Brazil","BR"],
    ["ZZ","Brazil","BR"],
    ["C6","Bahamas","BS"],
    ["A5","Bhutan","BT"],
    ["8O","Botswana","BW"],
    ["A2","Botswana","BW"],
    ["EU","Belarus","BY"],
    ["EV","Belarus","BY"],
    ["EW","Belarus","BY"],
    ["V3","Belize","BZ"],
    ["CF","Canada","CA"],
    ["CG","Canada","CA"],
    ["CH","Canada","CA"],
    ["CI","Canada","CA"],
    ["CJ","Canada","CA"],
    ["CK","Canada","CA"],
    ["CY","Canada","CA"],
    ["CZ","Canada","CA"],
    ["VA","Canada","CA"],
    ["VB","Canada","CA"],
    ["VC","Canada","CA"],
    ["VD","Canada","CA"],
    ["VE","Canada","CA"],
    ["VF","Canada","CA"],
    ["VG","Canada","CA"],
    ["VX","Canada","CA"],
    ["VY","Canada","CA"],
    ["XJ","Canada","CA"],
    ["XK","Canada","CA"],
    ["XL","Canada","CA"],
    ["XM","Canada","CA"],
    ["XN","Canada","CA"],
    ["XO","Canada","CA"],
    ["VO","Canada","CA"],
    ["9O","Congo","CG"],
    ["9P","Congo","CG"],
    ["9Q","Congo","CG"],
    ["9R","Congo","CG"],
    ["9S","Congo","CG"],
    ["9T","Congo","CG"],
    ["TN","Congo","CG"],
    ["HB","Switzerland","CH"],
    ["HE","Switzerland","CH"],
    ["E5","Cook Islands","CK"],
    ["3G","Chile","CL"],
    ["CA","Chile","CL"],
    ["CB","Chile","CL"],
    ["CC","Chile","CL"],
    ["CD","Chile","CL"],
    ["CE","Chile","CL"],
    ["XQ","Chile","CL"],
    ["XR","Chile","CL"],
    ["TJ","Cameroon","CM"],
    ["3H","China","CN"],
    ["3I","China","CN"],
    ["3J","China","CN"],
    ["3K","China","CN"],
    ["3L","China","CN"],
    ["3M","China","CN"],
    ["3N","China","CN"],
    ["3O","China","CN"],
    ["3P","China","CN"],
    ["3Q","China","CN"],
    ["3R","China","CN"],
    ["3S","China","CN"],
    ["3T","China","CN"],
    ["3U","China","CN"],
    ["XS","China","CN"],
    ["5J","Colombia","CO"],
    ["5K","Colombia","CO"],
    ["HJ","Colombia","CO"],
    ["HK","Colombia","CO"],
    ["TE","Costa Rica","CR"],
    ["TI","Costa Rica","CR"],
    ["Z6","Kosovo","CS"],
    ["CL","Cuba","CU"],
    ["CM","Cuba","CU"],
    ["CO","Cuba","CU"],
    ["T4","Cuba","CU"],
    ["D4","Cape Verde","CV"],
    ["5B","Cyprus","CY"],
    ["C4","Cyprus","CY"],
    ["H2","Cyprus","CY"],
    ["P3","Cyprus","CY"],
    ["OK","Czech Republic","CZ"],
    ["OL","Czech Republic","CZ"],
    ["DA","Germany","DE"],
    ["DB","Germany","DE"],
    ["DC","Germany","DE"],
    ["DD","Germany","DE"],
    ["DE","Germany","DE"],
    ["DF","Germany","DE"],
    ["DG","Germany","DE"],
    ["DH","Germany","DE"],
    ["DI","Germany","DE"],
    ["DJ","Germany","DE"],
    ["DK","Germany","DE"],
    ["DL","Germany","DE"],
    ["DM","Germany","DE"],
    ["DN","Germany","DE"],
    ["DO","Germany","DE"],
    ["DP","Germany","DE"],
    ["DQ","Germany","DE"],
    ["DR","Germany","DE"],
    ["Y2","Germany","DE"],
    ["Y3","Germany","DE"],
    ["Y4","Germany","DE"],
    ["Y5","Germany","DE"],
    ["Y6","Germany","DE"],
    ["Y7","Germany","DE"],
    ["Y8","Germany","DE"],
    ["Y9","Germany","DE"],
    ["J2","Djibouti","DJ"],
    ["5P","Denmark","DK"],
    ["5Q","Denmark","DK"],
    ["OU","Denmark","DK"],
    ["OV","Denmark","DK"],
    ["OW","Denmark","DK"],
    ["OX","Denmark","DK"],
    ["OY","Denmark","DK"],
    ["OZ","Denmark","DK"],
    ["XP","Denmark","DK"],
    ["J7","Dominica","DM"],
    ["HI","Dominican Republic","DO"],
    ["7R","Algeria","DZ"],
    ["7T","Algeria","DZ"],
    ["7U","Algeria","DZ"],
    ["7V","Algeria","DZ"],
    ["7W","Algeria","DZ"],
    ["7X","Algeria","DZ"],
    ["7Y","Algeria","DZ"],
    ["HC","Ecuador","EC"],
    ["HD","Ecuador","EC"],
    ["ES","Estonia","EE"],
    ["6A","Egypt","EG"],
    ["6B","Egypt","EG"],
    ["SU","Egypt","EG"],
    ["S0","Western Sahara","EH"],
    ["E3","Eritrea","ER"],
    ["AM","Spain","ES"],
    ["AN","Spain","ES"],
    ["AO","Spain","ES"],
    ["EA","Spain","ES"],
    ["EB","Spain","ES"],
    ["EC","Spain","ES"],
    ["ED","Spain","ES"],
    ["EE","Spain","ES"],
    ["EF","Spain","ES"],
    ["EG","Spain","ES"],
    ["EH","Spain","ES"],
    ["9E","Ethiopia","ET"],
    ["9F","Ethiopia","ET"],
    ["ET","Ethiopia","ET"],
    ["OF","Finland","FI"],
    ["OG","Finland","FI"],
    ["OH","Finland","FI"],
    ["OI","Finland","FI"],
    ["OJ","Finland","FI"],
    ["V6","Micronesia","FM"],
    ["TR","Gabon","GA"],
    ["VP","UK","GB"],
    ["VQ","UK","GB"],
    ["ZB","UK","GB"],
    ["ZC","UK","GB"],
    ["ZD","UK","GB"],
    ["ZE","UK","GB"],
    ["ZF","UK","GB"],
    ["ZG","UK","GB"],
    ["ZH","UK","GB"],
    ["ZI","UK","GB"],
    ["ZJ","UK","GB"],
    ["ZN","UK","GB"],
    ["ZO","UK","GB"],
    ["ZQ","UK","GB"],
    ["VS","UK","GB"],
    ["J3","Grenada","GD"],
    ["4L","Georgia","GE"],
    ["9G","Ghana","GH"],
    ["C5","The Gambia","GM"],
    ["3X","Guinea","GN"],
    ["3C","Equatorial Guinea","GQ"],
    ["J4","Greece","GR"],
    ["SV","Greece","GR"],
    ["SW","Greece","GR"],
    ["SX","Greece","GR"],
    ["SY","Greece","GR"],
    ["SZ","Greece","GR"],
    ["TD","Guatemala","GT"],
    ["TG","Guatemala","GT"],
    ["J5","Guinea-Bissau","GW"],
    ["8R","Guyana","GY"],
    ["VR","Hong Kong","HK"],
    ["HQ","Honduras","HN"],
    ["HR","Honduras","HN"],
    ["9A","Croatia","HR"],
    ["4V","Haiti","HT"],
    ["HH","Haiti","HT"],
    ["HA","Hungary","HU"],
    ["HG","Hungary","HU"],
    ["7A","Indonesia","ID"],
    ["7B","Indonesia","ID"],
    ["7C","Indonesia","ID"],
    ["7D","Indonesia","ID"],
    ["7E","Indonesia","ID"],
    ["7F","Indonesia","ID"],
    ["7G","Indonesia","ID"],
    ["7H","Indonesia","ID"],
    ["7I","Indonesia","ID"],
    ["8A","Indonesia","ID"],
    ["8B","Indonesia","ID"],
    ["8C","Indonesia","ID"],
    ["8D","Indonesia","ID"],
    ["8E","Indonesia","ID"],
    ["8F","Indonesia","ID"],
    ["8G","Indonesia","ID"],
    ["8H","Indonesia","ID"],
    ["8I","Indonesia","ID"],
    ["JZ","Indonesia","ID"],
    ["PK","Indonesia","ID"],
    ["PL","Indonesia","ID"],
    ["PM","Indonesia","ID"],
    ["PN","Indonesia","ID"],
    ["PO","Indonesia","ID"],
    ["YB","Indonesia","ID"],
    ["YC","Indonesia","ID"],
    ["YD","Indonesia","ID"],
    ["YE","Indonesia","ID"],
    ["YF","Indonesia","ID"],
    ["YG","Indonesia","ID"],
    ["YH","Indonesia","ID"],
    ["EI","Ireland","IE"],
    ["EJ","Ireland","IE"],
    ["4X","Israel","IL"],
    ["4Z","Israel","IL"],
    ["8T","India","IN"],
    ["8U","India","IN"],
    ["8V","India","IN"],
    ["8W","India","IN"],
    ["8X","India","IN"],
    ["8Y","India","IN"],
    ["AT","India","IN"],
    ["AU","India","IN"],
    ["AV","India","IN"],
    ["AW","India","IN"],
    ["VT","India","IN"],
    ["VU","India","IN"],
    ["VV","India","IN"],
    ["VW","India","IN"],
    ["HN","Iraq","IQ"],
    ["YI","Iraq","IQ"],
    ["9B","Iran","IR"],
    ["9C","Iran","IR"],
    ["9D","Iran","IR"],
    ["EP","Iran","IR"],
    ["EQ","Iran","IR"],
    ["TF","Iceland","IS"],
    ["6Y","Jamaica","JM"],
    ["JY","Jordan","JO"],
    ["7J","Japan","JP"],
    ["7K","Japan","JP"],
    ["7L","Japan","JP"],
    ["7M","Japan","JP"],
    ["7N","Japan","JP"],
    ["8J","Japan","JP"],
    ["8K","Japan","JP"],
    ["8L","Japan","JP"],
    ["8M","Japan","JP"],
    ["8N","Japan","JP"],
    ["JA","Japan","JP"],
    ["JB","Japan","JP"],
    ["JC","Japan","JP"],
    ["JD","Japan","JP"],
    ["JE","Japan","JP"],
    ["JF","Japan","JP"],
    ["JG","Japan","JP"],
    ["JH","Japan","JP"],
    ["JI","Japan","JP"],
    ["JJ","Japan","JP"],
    ["JK","Japan","JP"],
    ["JL","Japan","JP"],
    ["JM","Japan","JP"],
    ["JN","Japan","JP"],
    ["JO","Japan","JP"],
    ["JP","Japan","JP"],
    ["JQ","Japan","JP"],
    ["JR","Japan","JP"],
    ["JS","Japan","JP"],
    ["5Y","Kenya","KE"],
    ["5Z","Kenya","KE"],
    ["EX","Kyrgyzstan","KG"],
    ["XU","Cambodia","KH"],
    ["T3","Kiribati","KI"],
    ["D6","Comoros","KM"],
    ["V4","Saint Kitts and Nevis","KN"],
    ["HM","North Korea","KP"],
    ["P5","North Korea","KP"],
    ["P6","North Korea","KP"],
    ["P7","North Korea","KP"],
    ["P8","North Korea","KP"],
    ["P9","North Korea","KP"],
    ["6K","South Korea","KR"],
    ["6L","South Korea","KR"],
    ["6M","South Korea","KR"],
    ["6N","South Korea","KR"],
    ["D7","South Korea","KR"],
    ["D8","South Korea","KR"],
    ["D9","South Korea","KR"],
    ["DS","South Korea","KR"],
    ["DT","South Korea","KR"],
    ["HL","South Korea","KR"],
    ["9K","Kuwait","KW"],
    ["UN","Kazakhstan","KZ"],
    ["UO","Kazakhstan","KZ"],
    ["UP","Kazakhstan","KZ"],
    ["UQ","Kazakhstan","KZ"],
    ["XW","Laos","LA"],
    ["OD","Lebanon","LB"],
    ["J6","Saint Lucia","LC"],
    ["4P","Sri Lanka","LK"],
    ["4Q","Sri Lanka","LK"],
    ["4R","Sri Lanka","LK"],
    ["4S","Sri Lanka","LK"],
    ["5L","Liberia","LR"],
    ["5M","Liberia","LR"],
    ["6Z","Liberia","LR"],
    ["A8","Liberia","LR"],
    ["D5","Liberia","LR"],
    ["EL","Liberia","LR"],
    ["7P","Lesotho","LS"],
    ["LY","Lithuania","LT"],
    ["LX","Luxembourg","LU"],
    ["YL","Latvia","LV"],
    ["5A","Libya","LY"],
    ["5C","Morocco","MA"],
    ["5D","Morocco","MA"],
    ["5E","Morocco","MA"],
    ["5F","Morocco","MA"],
    ["5G","Morocco","MA"],
    ["CN","Morocco","MA"],
    ["3A","Monaco","MC"],
    ["ER","Moldova","MD"],
    ["4O","Montenegro","ME"],
    ["5R","Madagascar","MG"],
    ["5S","Madagascar","MG"],
    ["6X","Madagascar","MG"],
    ["V7","Marshall Islands","MH"],
    ["TZ","Mali","ML"],
    ["JT","Mongolia","MN"],
    ["JU","Mongolia","MN"],
    ["JV","Mongolia","MN"],
    ["5T","Mauritania","MR"],
    ["1A","Malta","MT"],
    ["9H","Malta","MT"],
    ["3B","Mauritius","MU"],
    ["8Q","Maldives","MV"],
    ["7Q","Malawi","MW"],
    ["4A","Mexico","MX"],
    ["4B","Mexico","MX"],
    ["4C","Mexico","MX"],
    ["6D","Mexico","MX"],
    ["6E","Mexico","MX"],
    ["6F","Mexico","MX"],
    ["6G","Mexico","MX"],
    ["6H","Mexico","MX"],
    ["6I","Mexico","MX"],
    ["6J","Mexico","MX"],
    ["XA","Mexico","MX"],
    ["XB","Mexico","MX"],
    ["XC","Mexico","MX"],
    ["XD","Mexico","MX"],
    ["XE","Mexico","MX"],
    ["XF","Mexico","MX"],
    ["XG","Mexico","MX"],
    ["XH","Mexico","MX"],
    ["XI","Mexico","MX"],
    ["9M","Malaysia","MY"],
    ["9W","Malaysia","MY"],
    ["C8","Mozambique","MZ"],
    ["C9","Mozambique","MZ"],
    ["V5","Namibia","NA"],
    ["5U","Niger","NE"],
    ["5N","Nigeria","NG"],
    ["5O","Nigeria","NG"],
    ["H6","Nicaragua","NI"],
    ["H7","Nicaragua","NI"],
    ["HT","Nicaragua","NI"],
    ["YN","Nicaragua","NI"],
    ["PA","Netherlands","NL"],
    ["PB","Netherlands","NL"],
    ["PC","Netherlands","NL"],
    ["PD","Netherlands","NL"],
    ["PE","Netherlands","NL"],
    ["PF","Netherlands","NL"],
    ["PG","Netherlands","NL"],
    ["PH","Netherlands","NL"],
    ["PI","Netherlands","NL"],
    ["3Y","Norway","NO"],
    ["JW","Norway","NO"],
    ["JX","Norway","NO"],
    ["LA","Norway","NO"],
    ["LB","Norway","NO"],
    ["LC","Norway","NO"],
    ["LD","Norway","NO"],
    ["LE","Norway","NO"],
    ["LF","Norway","NO"],
    ["LG","Norway","NO"],
    ["LH","Norway","NO"],
    ["LI","Norway","NO"],
    ["LJ","Norway","NO"],
    ["LK","Norway","NO"],
    ["LL","Norway","NO"],
    ["LM","Norway","NO"],
    ["LN","Norway","NO"],
    ["9N","Nepal","NP"],
    ["C2","Nauru","NR"],
    ["E6","Niue","NU"],
    ["ZK","New Zealand","NZ"],
    ["ZL","New Zealand","NZ"],
    ["ZM","New Zealand","NZ"],
    ["A4","Oman","OM"],
    ["3E","Panama","PA"],
    ["3F","Panama","PA"],
    ["H3","Panama","PA"],
    ["H8","Panama","PA"],
    ["H9","Panama","PA"],
    ["HO","Panama","PA"],
    ["HP","Panama","PA"],
    ["4T","Peru","PE"],
    ["OA","Peru","PE"],
    ["OB","Peru","PE"],
    ["OC","Peru","PE"],
    ["P2","Papua New Guinea","PG"],
    ["4D","Philippines","PH"],
    ["4E","Philippines","PH"],
    ["4F","Philippines","PH"],
    ["4G","Philippines","PH"],
    ["4H","Philippines","PH"],
    ["4I","Philippines","PH"],
    ["DU","Philippines","PH"],
    ["DV","Philippines","PH"],
    ["DW","Philippines","PH"],
    ["DX","Philippines","PH"],
    ["DY","Philippines","PH"],
    ["DZ","Philippines","PH"],
    ["6P","Pakistan","PK"],
    ["6Q","Pakistan","PK"],
    ["6R","Pakistan","PK"],
    ["6S","Pakistan","PK"],
    ["AP","Pakistan","PK"],
    ["AQ","Pakistan","PK"],
    ["AR","Pakistan","PK"],
    ["AS","Pakistan","PK"],
    ["3Z","Poland","PL"],
    ["HF","Poland","PL"],
    ["SN","Poland","PL"],
    ["SO","Poland","PL"],
    ["SP","Poland","PL"],
    ["SQ","Poland","PL"],
    ["SR","Poland","PL"],
    ["E4","Palestine","PS"],
    ["CQ","Portugal","PT"],
    ["CR","Portugal","PT"],
    ["CS","Portugal","PT"],
    ["CT","Portugal","PT"],
    ["CU","Portugal","PT"],
    ["T8","Palau","PW"],
    ["ZP","Paraguay","PY"],
    ["A7","Qatar","QA"],
    ["YO","Romania","RO"],
    ["YP","Romania","RO"],
    ["YQ","Romania","RO"],
    ["YR","Romania","RO"],
    ["YT","Serbia","RS"],
    ["YU","Serbia","RS"],
    ["UA","Russia","RU"],
    ["UB","Russia","RU"],
    ["UC","Russia","RU"],
    ["UD","Russia","RU"],
    ["UE","Russia","RU"],
    ["UF","Russia","RU"],
    ["UG","Russia","RU"],
    ["UH","Russia","RU"],
    ["UI","Russia","RU"],
    ["9X","Rwanda","RW"],
    ["7Z","Saudi Arabia","SA"],
    ["8Z","Saudi Arabia","SA"],
    ["HZ","Saudi Arabia","SA"],
    ["H4","Solomon Islands","SB"],
    ["S7","Seychelles","SC"],
    ["6T","Sudan","SD"],
    ["6U","Sudan","SD"],
    ["SS","Sudan","SD"],
    ["ST","Sudan","SD"],
    ["7S","Sweden","SE"],
    ["8S","Sweden","SE"],
    ["SA","Sweden","SE"],
    ["SB","Sweden","SE"],
    ["SC","Sweden","SE"],
    ["SD","Sweden","SE"],
    ["SE","Sweden","SE"],
    ["SF","Sweden","SE"],
    ["SG","Sweden","SE"],
    ["SH","Sweden","SE"],
    ["SI","Sweden","SE"],
    ["SJ","Sweden","SE"],
    ["SK","Sweden","SE"],
    ["SL","Sweden","SE"],
    ["SM","Sweden","SE"],
    ["9V","Singapore","SG"],
    ["S6","Singapore","SG"],
    ["S5","Slovenia","SI"],
    ["9L","Sierra Leone","SL"],
    ["T7","San Marino","SM"],
    ["6V","Senegal","SN"],
    ["6W","Senegal","SN"],
    ["6O","Somalia","SO"],
    ["T5","Somalia","SO"],
    ["PZ","Suriname","SR"],
    ["Z8","South Sudan","SS"],
    ["HU","El Salvador","SV"],
    ["YS","El Salvador","SV"],
    ["6C","Syria","SY"],
    ["YK","Syria","SY"],
    ["TT","Chad","TD"],
    ["HW","French Terr.","TF"],
    ["HX","French Terr.","TF"],
    ["HY","French Terr.","TF"],
    ["TH","French Terr.","TF"],
    ["TK","French Terr.","TF"],
    ["TM","French Terr.","TF"],
    ["TO","French Terr.","TF"],
    ["TP","French Terr.","TF"],
    ["TQ","French Terr.","TF"],
    ["TV","French Terr.","TF"],
    ["TW","French Terr.","TF"],
    ["TX","French Terr.","TF"],
    ["5V","Togo","TG"],
    ["E2","Thailand","TH"],
    ["HS","Thailand","TH"],
    ["EY","Tajikistan","TJ"],
    ["EZ","Turkmenistan","TM"],
    ["3V","Tunisia","TN"],
    ["TS","Tunisia","TN"],
    ["A3","Tonga","TO"],
    ["TA","Turkey","TR"],
    ["TB","Turkey","TR"],
    ["TC","Turkey","TR"],
    ["YM","Turkey","TR"],
    ["9Y","Trinidad and Tobago","TT"],
    ["9Z","Trinidad and Tobago","TT"],
    ["T2","Tuvalu","TV"],
    ["BM","Taiwan","TW"],
    ["BN","Taiwan","TW"],
    ["BO","Taiwan","TW"],
    ["BP","Taiwan","TW"],
    ["BQ","Taiwan","TW"],
    ["BU","Taiwan","TW"],
    ["BV","Taiwan","TW"],
    ["BW","Taiwan","TW"],
    ["BX","Taiwan","TW"],
    ["5H","Tanzania","TZ"],
    ["5I","Tanzania","TZ"],
    ["EM","Ukraine","UA"],
    ["EN","Ukraine","UA"],
    ["EO","Ukraine","UA"],
    ["UR","Ukraine","UA"],
    ["US","Ukraine","UA"],
    ["UT","Ukraine","UA"],
    ["UU","Ukraine","UA"],
    ["UV","Ukraine","UA"],
    ["UW","Ukraine","UA"],
    ["UX","Ukraine","UA"],
    ["UY","Ukraine","UA"],
    ["UZ","Ukraine","UA"],
    ["5X","Uganda","UG"],
    ["AA","USA","US"],
    ["AB","USA","US"],
    ["AC","USA","US"],
    ["AD","USA","US"],
    ["AE","USA","US"],
    ["AF","USA","US"],
    ["AG","USA","US"],
    ["AH","USA","US"],
    ["AI","USA","US"],
    ["AJ","USA","US"],
    ["AK","USA","US"],
    ["AL","USA","US"],
    ["CV","Uruguay","UY"],
    ["CW","Uruguay","UY"],
    ["CX","Uruguay","UY"],
    ["UJ","Uzbekistan","UZ"],
    ["UK","Uzbekistan","UZ"],
    ["UL","Uzbekistan","UZ"],
    ["UM","Uzbekistan","UZ"],
    ["HV","Vatican","VA"],
    ["4M","Venezuela","VE"],
    ["YV","Venezuela","VE"],
    ["YW","Venezuela","VE"],
    ["YX","Venezuela","VE"],
    ["YY","Venezuela","VE"],
    ["3W","Vietnam","VN"],
    ["XV","Vietnam","VN"],
    ["YJ","Vanuatu","VU"],
    ["5W","Samoa","WS"],
    ["7O","Yemen","YE"],
    ["S8","South Africa","ZA"],
    ["ZR","South Africa","ZA"],
    ["ZS","South Africa","ZA"],
    ["ZT","South Africa","ZA"],
    ["ZU","South Africa","ZA"],
    ["9I","Zambia","ZM"],
    ["9J","Zambia","ZM"],
    ["Z2","Zimbabwe","ZW"],
    ["0S","Seborga",""],
    ["1B","Northern Cyprus or Blenheim Reef",""],
    ["1G","Geyser Reef",""],
    ["1L","Liberland",""],
    ["1M","Minerva Reefs",""],
    ["1S","Principality of Sealand",""],
    ["1Z","Kayin State",""],
    ["4U","United Nations",""],
    ["4W","East Timor",""],
    ["4Y","International Civil Aviation Organization",""],
    ["C7","World Meteorological Organization",""],
    ["D0","Donetsk",""],
    ["D1","Donetsk",""],
    ["H5","Bophuthatswana",""],
    ["J8","Saint Vincent and the Grenadines",""],
    ["O1","South Ossetia",""],
    ["OM","Slovakia","SK"],
    ["PJ","Neth. Antilles",""],
    ["S9","São Tomé and Príncipe",""],
    ["T0","Principality of Seborga",""],
    ["T1","Transnistria",""],
    ["TL","Central Africa","CF"],
    ["TU","Ivory Coast",""],
    ["XX","Macao",""],
    ["XY","Burma",""],
    ["XZ","Burma",""],
    ["Z3","Republic of Macedonia",""],
    ["B","China","CN"],
    ["2","UK","GB"],
    ["G","UK","GB"],
    ["M","UK","GB"],
    ["I","Italy","IT"],
    ["R","Russia","RU"],
    ["K","USA","US"],
    ["N","USA","US"],
    ["W","USA","US"],
    ["F","France","FR"]
];
